### ISSUE TITLE
Proof it works!

### ISSUE THREAD

**Issue by ghost** [arpitjindal97/resin-route#1]
This is so awesome and it works on resinOS now. Wow, such h@ckr! Please connect with me on keybase so I can reward you for your efforts.

![screenshot_20180611_214642](https://user-images.githubusercontent.com/440298/41235787-0aa7f81a-6d7f-11e8-862e-80be8da7cb4c.jpg)
![screenshot_20180611-214740](https://user-images.githubusercontent.com/440298/41235824-229c3580-6d7f-11e8-9f0c-ff2c52a595fc.jpg)

**Comment by jhabdas** [comment]
Another speed test using WiFi lifted from ZTE Corporation, a Chinese company used as an ISP to censor Internet in Indonesia. Clocked from Bali while concurrently streaming iTunes videos over an Apple TV. 
![screenshot_20180612_083803](https://user-images.githubusercontent.com/440298/41263989-cb8425e0-6dd9-11e8-965e-e51692565548.jpg)
Quick and dirty setup instructions here: https://talk.balibebas.com/t/apple-tv-not-playing-itunes-movies-in-indonesia/80/4

**Comment by jhabdas** [comment]
Quick and dirty setup instructions here: https://talk.balibebas.com/t/apple-tv-not-playing-itunes-movies-in-indonesia/80/4

**Comment by jhabdas** [comment]
Quick and dirty setup instructions to use this to stream iTunes movies over Apple TV in Indonesia (otherwise blocked by ISPs like ZTE Corporation): https://talk.balibebas.com/t/apple-tv-not-playing-itunes-movies-in-indonesia/80/4

**Comment by jhabdas** [comment]
Quick and dirty setup instructions to use this to stream iTunes movies in HD over Apple TV in Indonesia (otherwise blocked by ISPs like ZTE Corporation): https://talk.balibebas.com/t/apple-tv-not-playing-itunes-movies-in-indonesia/80/4

Speeds higher than 20Mbps have been witnessed before use of VPN, Tor, I2P.

**Comment by ghost** [comment]
Quick and dirty setup instructions to use this to stream iTunes movies in HD over Apple TV in Indonesia (otherwise blocked by ISPs):

https://talk.balibebas.com/t/apple-tv-not-playing-itunes-movies-in-indonesia/80/4

Speeds higher than 20Mbps have been witnessed before use of VPN, Tor, I2P.

**Comment by ghost** [comment]
Here're results of another test of the network captured using the Meteor app for Android. This test was taken with TunnelBear VPN activated using the GhostBear feature, which is intended to disguise encrypted traffic as normal traffic, with TLS to a cheapo RT-N12+ router jacked into the RPi with a 1 meter Ethernet cable lifting a signal from a public WiFi router located within 3 meters without any physical obstructions.

![screenshot_20180619_010429](https://user-images.githubusercontent.com/440298/41551076-46b16b8e-731a-11e8-9264-079eb215711a.jpg)

A note on the speed. I'm getting about 14Mbps down on large binaries when testing from both on the resinOS rootFS as well as inside the container and the router is 100Mbps and brand new so the bottleneck I'm seeing is likely either the ethernet interface, the cord itself or simply [PEBKAC](https://xkcd.com/1328/).
